apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: default
spec:
  encryptedData:
    password: AgAshGLzUg3MXOduXbjmxBe95VztPjUn1hsJFCZChAHwEbG+7lCn7OHnDSdeifGWcsDJWoIHznnu3EHBjww7Lgcpvxx5GxFkqt31599HCn7gpfJbfHLB8GN4QQ5Q59SwxVeBIRxec975G6kTzs7f1INR5bbQ5kmR6fhnbJXPbNYpXuzFY985eL17l/HkSakcn6utant19P98GjRsw6SUBK0KmkQcfDFZoODhwZqqw5OnAHwo8uXzNsU6TiMMf4CIoqrsWG5064r+lB5cZ7GX1Fc0zHelhwHEoiKRVMjMwQg5ZcQpSDDJYoMHDNdjFC4ITqZPw+b3Yb5aGFE1uQjbiQbQSeMCaWibjIa9viMY17WYb5AhibZSYiqV2wfgGzD+lgXKmov6aXWVWnN/Niq4Z1jflrEELBKnigIIppPqM9DlGRnGxwZm/YLGHicFjUz3Kx/yubf/DXvUg3GLVuyT/KfF+qRf5YiUFmYiGiz90Dk5kOpbvFYIEBQUK/LFr8e4NlLxdWuSc/tV3b1kuYR4eFKVlsUFnc54veAisfyuRHu1jqax+zlKkDkkB5Vvqt739wFhGFIS0b5jPq5JfsS04bTexrrepN0iExANYKX7qFYLYz+2uD5Pmir9tiMTuJAjAj2CeHXeBQ1M6s+3aJz3mrJ+ZpOeoBldZst/jEI1UYsA9TYY2NU3raxnhs2PCi4EqiCUZq4HM1m/4GM=
    user: AgBRWVCfp2KthRrPs7lxXWGpLF8RhlkUCo9d3lywjXFzzxqp022aezN0VxxHLTTZp9FqeC2aiSRohTvkFU9ddIhMi+v7pxT52nYTWh7TpMMwyUeNisNPsTGgohJePwWXLFKO39ht1L3xniWB2hzQz6fPx2TDIeYQfN8IDcADxDnm5JBBzzw+uPvBH/96BCn4S6YCFcEhcyGHJOnEA2G1RZpWfjB788veItukszid154nOYmh9CHvpid1yyQnrdRo7xtq1b1CTjqRt8y/dosCCcDDUr1BDbapodrK/ysP1LKBQglY1o6uTkfF94e+6HIyQ1vUK6Os3P0yvlzhoaIJSkyPwDxyB6hmFNmzXM3zkyBWL0hz6KRcUCXjewaVnOmANLy2aY797Xuvqs0MfcodgWlJCj34i3uNgrNMcmkHlZhGckZ3VqR0o2yZ5lsTMpJQr04/arlR8zKC3uvnZpzauHNJPXEZaHSlYAkBPSaIO5tsBNH7UGPY6CzE3jznMH/cAoWeDIxdllyRGkoE7KVnQi+dfunfXxAO+n0Keds3Zdo6bYqIYiezTxLXyTap2IRJ95K1ssCJXfekHyZsL2OEV0/BffMTj+9e2Oex1GY9d+5VX0+vEYc75BIDjGM5ejV+uK+VjamIqvLlOvybnd6EIDIRJ6uK61bQBhlpizg2ZRApt9i9DKVJYENfH6QCZTQ0E/Zv+QkpWg==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: default
