apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: default
spec:
  encryptedData:
    password: AgCR67yjYfRtj++ZtR0hZi5KwNHmqzt0UFDApOUpuBQjWt+B53OMPenoHjJvBSp9Is6NqvoEFwtXZASsplmWDvypVMnas12ZKmw2ekVzIJ7oP3o1WIup7TOIPvsHaMk5kM+hFPcGH6qxKLWdEYwouj6gpQNzfRaJmFPoM+ssONBbWmNy6X0VU6JEvJ47c3rSPb1YVOxCdF+nuZGAxbtmg2ZloJiU7YL4w0GiZa3RFnrhDTK4FpHhNmM4JBUoID3vpq6pJ0+P5bMTUQsqHl172Pk43Yl8J1R81LLmwltZZL6ZuwuqLjjLWj2KLAuInPvGZn+RkJe0ExVT6GUCgQT296wOK78+LWmpC+EHkAvYKfq8+rz3/YnsD15gHz8ANeVPLOPxDR12J9MqJ4t3M05LZHW8FfLpCDkohYlCQh97Cw/d2r6GwzgYskoXFNNDGUA67UqdpgGizJzclSUSOopD8UJGu1YkoP6Uq63LfFwG3+UqyUuzpOQl5ncdvUsydMrXcNATvHxcafJpETEZgIFLvAGtf+Nf04WZG0h/xitr9apvN/REu409RQrxuLkpWybhDUj8prDIwrr4CHXlRg5Yco0YbTSUmSo0HlgcUPB7lgI6ihEc7sYyNNcWn0patqZQU2aNzhtgCWWrU6+iF6gjdykKSxmxenY6S6Ju7DoR2eecWpVDC7ErBqF/XhSL/XNMthqbBbpp8xv7iAQ=
    user: AgB8FIpw7HBNAhg8sI+f2KKLUXKOQl/vy8CzsSDd14/ZIxiUz4ePMoF1AWUzHmP3jv7VXzsrvZsZNC2TH3JBBJkJbaio7/vM2V7bsZzOO2Kvb6sorqNMm3Krboqlpv1w3PQSJ6JXZNBXu2RXPGlbskRzOFOX/Fwm/8ZddAJKQdwb2C5TlqcsU4iERZEs77vF05H32YDkTljbaXwxuCiY+9rl9fyg7g5D9c5eRxas6CF7n4F4UrWEAsWajvpnSw6BBpHLwz1Iw/DwY7ZtFp0GhSf9EFmVGNMIcMXvexz2DMhEnpoIiw7By4ZJxDjlvWv5nlAEwVZIbmxcMPT/8z6UBU4c9/KAuJ3IgcM74caJuqDN9Vd3bGxPydUrCOhMRYIwxUBzF6jMpNj/FPT2q/s8TNB/wHGmTt7MPUTvbbZ8txTL0EJnzJhNqODFEsO/FhBnKTLH0rrRF3dRa0ZPniuMOE3kv2Ctwy/7w6wfM7jjo2WbDOC8PbYDoOnu5oxAyqNUIqgTqZKdk9XNct+0S0098fSOO1lQx0AGVXM34GHbCd6/9jTc9tYJMWFMONWtClwO4u/5jHjLF6kFrXWWtndXz0ceSb4jtJmeX4RhpfDoaDIrSyIjYMKwjpft8lLwOX/8k1eItzABa2fpR/H4p4kShsKMLIwW83GfN+Op3FxSn/Fx3ujvCqZ1Abhi6Fy0Q1l3I6K4urjfuw==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: default
